-- Non-destructive migration for MCQ Bot v3.
-- Run this in Supabase SQL Editor. It does NOT delete your existing questions.

create extension if not exists pg_trgm;

create table if not exists public.ingest_queue (
  id bigint generated by default as identity primary key,
  telegram_update_id bigint unique,
  chat_id bigint not null,
  message_id bigint,
  file_id text not null,
  file_name text not null,
  mime_type text,
  file_size bigint default 0,
  status text not null default 'queued' check (status in ('queued','processing','done','failed')),
  attempts integer not null default 0,
  progress integer not null default 0,
  total_items integer not null default 0,
  saved_count integer not null default 0,
  duplicate_count integer not null default 0,
  error_message text,
  next_run_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create index if not exists ingest_queue_pick_idx
  on public.ingest_queue(status, next_run_at, created_at);

alter table public.questions add column if not exists normalized_question text;

create unique index if not exists questions_content_hash_uidx
  on public.questions(content_hash)
  where content_hash is not null;

create index if not exists questions_normalized_trgm_idx
  on public.questions using gin (normalized_question gin_trgm_ops);

-- Fill the new normalization column for existing rows.
update public.questions
set normalized_question = lower(regexp_replace(coalesce(question_text,''), '[^[:alnum:][:space:]]', '', 'g'))
where normalized_question is null;

create or replace function public.claim_ingest_job()
returns setof public.ingest_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  picked_id bigint;
begin
  select id into picked_id
  from public.ingest_queue
  where status = 'queued'
    and next_run_at <= now()
  order by created_at
  for update skip locked
  limit 1;

  if picked_id is null then
    return;
  end if;

  update public.ingest_queue
  set status='processing', attempts=attempts+1, started_at=now(), updated_at=now()
  where id=picked_id;

  return query select * from public.ingest_queue where id=picked_id;
end;
$$;

create or replace function public.find_similar_question(p_question text, p_threshold real default 0.88)
returns table(id bigint, question_text text, similarity real)
language sql
security definer
set search_path = public
as $$
  select q.id, q.question_text,
         similarity(q.normalized_question,
           lower(regexp_replace(coalesce(p_question,''), '[^[:alnum:][:space:]]', '', 'g'))) as similarity
  from public.questions q
  where q.normalized_question is not null
    and similarity(q.normalized_question,
      lower(regexp_replace(coalesce(p_question,''), '[^[:alnum:][:space:]]', '', 'g'))) >= p_threshold
  order by similarity desc
  limit 3;
$$;

-- Useful for the bot's /stats command.
create or replace function public.question_category_stats()
returns table(exam_name text, subject_name text, chapter_name text, question_count bigint)
language sql
security definer
set search_path = public
as $$
  select coalesce(exam_name,'General')::text,
         coalesce(subject_name,'General')::text,
         coalesce(chapter_name,'General')::text,
         count(*)
  from public.questions
  group by exam_name, subject_name, chapter_name
  order by count(*) desc;
$$;

alter table public.ingest_queue add column if not exists job_type text not null default 'file' check (job_type in ('file','scrape'));
alter table public.ingest_queue alter column file_id drop not null;
alter table public.ingest_queue alter column file_name drop not null;
alter table public.ingest_queue add column if not exists target_count integer default 500;
