
-- V5 combined migration: NCERT verification + evidence/source tracking.
-- SAFE: additive only; does not delete existing questions.

alter table public.questions
  add column if not exists verification_status text default 'PENDING',
  add column if not exists verified_answer text,
  add column if not exists verification_reason text,
  add column if not exists ncert_class text,
  add column if not exists ncert_subject text,
  add column if not exists ncert_chapter text,
  add column if not exists ncert_source_title text,
  add column if not exists ncert_source_url text,
  add column if not exists ncert_source_page text,
  add column if not exists ncert_source_excerpt text,
  add column if not exists ncert_evidence_hash text,
  add column if not exists verified_at timestamptz,
  add column if not exists verification_provider text,
  add column if not exists verification_model text;

create table if not exists public.ncert_sources (
  id bigint generated by default as identity primary key,
  title text not null,
  class_level text,
  subject text,
  chapter text,
  source_url text not null unique,
  source_type text default 'NCERT_OFFICIAL',
  content_hash text,
  retrieved_at timestamptz default now(),
  is_active boolean default true
);

create table if not exists public.ncert_verification_jobs (
  id bigint generated by default as identity primary key,
  question_id bigint,
  status text default 'QUEUED',
  ncert_class text,
  ncert_subject text,
  ncert_chapter text,
  source_url text,
  source_title text,
  source_page text,
  evidence_excerpt text,
  verified_answer text,
  verification_reason text,
  verification_provider text,
  verification_model text,
  started_at timestamptz,
  completed_at timestamptz,
  error_message text
);

create index if not exists idx_questions_verification_status
  on public.questions(verification_status);

create index if not exists idx_ncert_jobs_status
  on public.ncert_verification_jobs(status);
